include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: warning
    missing_return: warning
    todo: ignore
    sdk_version_async_exported_from_core: ignore
  exclude:
    - "bin/cache/**"
    - "lib/i18n/messages_*.dart"
    - "lib/src/http/**"

linter:
  rules:
