name: wrale
description: "wrale - privacy-respecting body weight-diary"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.6.9
  hive_flutter: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  introduction_screen: ^3.1.12
  flutter_svg: ^2.0.9
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
